let server_addr="http://live.aiolos.com";

let apiUrl = "/live-api";
let userUrl = "/live-user-provider"
let sendSmsUrl = server_addr + apiUrl + "/sms/send-sms";
let loginUrl = server_addr + userUrl + "/user/login";
let homePageUrl = server_addr + apiUrl + "/home/init-page";
let startLiving = server_addr + apiUrl + "/living-room/start-streaming";
let closeLiving = server_addr + apiUrl + "/living-room/stop-streaming";
let anchorConfigUrl = server_addr + apiUrl + "/living-room/anchorConfig";
let listLivingRoomUrl = server_addr + apiUrl +"/living-room/list";
let getImConfigUrl = server_addr + apiUrl + "/im/getImConfig";
let listGiftConfigUrl = server_addr + apiUrl + "/gift/listGift";
let sendGiftUrl = server_addr + apiUrl + "/gift/send";
let payProductsUrl = server_addr + apiUrl + "/bank/products";
let payProductUrl = server_addr + apiUrl + "/bank/payProduct";
let onlinePkUrl = server_addr + apiUrl + "/living/onlinePk";
let prepareRedPacketUrl = server_addr + apiUrl + "/living/prepareRedPacket";
let startRedPacketUrl = server_addr + apiUrl + "/living/startRedPacket";
let getRedPacketUrl = server_addr + apiUrl + "/living/getRedPacket";
let queryShopInfoUrl = server_addr + apiUrl + "/shop/listSkuInfo";
let queryShopDetailInfoUrl = server_addr + apiUrl + "/shop/detail";
let addShopCarUrl = server_addr + apiUrl + "/shop/addCar";
let getCarInfoUrl = server_addr + apiUrl + "/shop/getCarInfo";
let removeFromCarUrl = server_addr + apiUrl + "/shop/removeFromCar"
let createPrepareOrderInfoUrl = server_addr + apiUrl + "/shop/prepareOrder";
let payNowUrl = server_addr + apiUrl +"/shop/payNow";