let server_addr="http://live.aiolos.com";
window.loginCenterUrl = "http://www.aiolos.com:5502/";

let apiUrl = "/live-api";
let imUrl = "/live-im-provider"
let livingUrl = "/live-living-provider"
let userUrl = "/badger-user-provider"

let homePageUrl = server_addr + livingUrl + "/home/init-page";
let startLiving = server_addr + livingUrl + "/living-room/start-streaming";
let closeLiving = server_addr + livingUrl + "/living-room/stop-streaming";
let anchorConfigUrl = server_addr + livingUrl + "/living-room/anchor-config";
let listLivingRoomUrl = server_addr + livingUrl +"/living-room/list";
let getImConfigUrl = server_addr + imUrl + "/im/get-im-config";
let listGiftConfigUrl = server_addr + apiUrl + "/gift/listGift";
let sendGiftUrl = server_addr + apiUrl + "/gift/send";
let payProductsUrl = server_addr + apiUrl + "/bank/products";
let payProductUrl = server_addr + apiUrl + "/bank/payProduct";
let onlinePkUrl = server_addr + apiUrl + "/living/onlinePk";
let prepareRedPacketUrl = server_addr + apiUrl + "/living/prepareRedPacket";
let startRedPacketUrl = server_addr + apiUrl + "/living/startRedPacket";
let getRedPacketUrl = server_addr + apiUrl + "/living/getRedPacket";
let queryShopInfoUrl = server_addr + apiUrl + "/shop/listSkuInfo";
let queryShopDetailInfoUrl = server_addr + apiUrl + "/shop/detail";
let addShopCarUrl = server_addr + apiUrl + "/shop/addCar";
let getCarInfoUrl = server_addr + apiUrl + "/shop/getCarInfo";
let removeFromCarUrl = server_addr + apiUrl + "/shop/removeFromCar"
let createPrepareOrderInfoUrl = server_addr + apiUrl + "/shop/prepareOrder";
let payNowUrl = server_addr + apiUrl +"/shop/payNow";
